version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./shopping-list-app/server/db_scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  server:
    build: ./shopping-list-app/server
    container_name: shopping-list-server
    environment:
      MONGO_URI: mongodb://mongodb:27017/shoppinglist
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  client:
    build: ./shopping-list-app/client
    container_name: shopping-list-client
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongodb_data:
